---
title: "iteration_and_listcols"
output: github_document
date: "2023-10-31"
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages 
```{r}
library(tidyverse)
library(rvest)
```

set seed for reproducibility
```{r}
set.seed(12345)
```


### lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(
  num = vec_numeric,
  char = vec_char
)
```

Different stuff with different lengths 

```{r}
vec_numeric = 1:5
vec_char = LETTERS
# tibble not going to work becuase they have different length, 5 vs. 26

l = list(
  vec_numeric = 1:5,
  vec_char = LETTERS,
  matrix = matrix (1:10, nrow = 5, ncol = 2),
  summary = summary(rnorm(100))
)
```

accessing lists

```{r}
l$vec_char # pull out using the name of the vector
l[[1]] # pull out the first items in the list 
l[["summary"]]  # pull out using the name of the vector
```

### loops 

```{r}
list_norm_samples = 
  list(
    a = rnorm(20,1,5),
    b = rnorm(20,0,7),
    c = rnorm(20,20,1),
    d = rnorm(20,-45,13)
  )
```

mean and standard deviation

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argurment should be numbers")
  } else if (length(x) <2) {
    stop("You need at least 2 number to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```


for loop
```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
```

### use `map`

```{r}
output = map(list_norm_samples, mean_and_sd) 
# (list I want the function to apply to, function)

output = map(list_norm_samples, median)

output = map(list_norm_samples, summary)
```

multiple function at once
```{r}
output_mean_sd = vector("list", length = 4)
output_median = vector("list", length = 4)

for (i in 1:4) {
  
  output_mean_sd[[i]] = mean_and_sd(list_norm_samples[[i]])
  output_median[[i]] = median(list_norm_samples[[i]])
}
```

```{r}
output_mean_sd = map(list_norm_samples, mean_and_sd) 
output_median = map(list_norm_samples, median)
output_summary = map(list_norm_samples, summary)
```


