---
title: "Writing_functions"
output: github_document
date: "2023-10-26"
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages 
```{r}
library(tidyverse)
library(rvest)
```

set seed for reproducibility
```{r}
set.seed(12345)
```

### z score function 

Z scores subtract the mean and divide by the sd
```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

compute Z scores for `x_vec`.

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```

Write a function to do this!

```{r}
z_score = function(x) {
  
  z = (x-mean(x)) / sd(x)
  
  z
  
  
  
}
```

check that this works,

```{r}
z_score(x = x_vec)
```

Keep checking 

```{r, error = TRUE}
z_score(x=3)

z_score(c("my", "name", "is", "jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)
```

```{r}
z_score = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argurment should be numbers")
  } else if (length(x) <2) {
    stop("You need at least 2 number to get z scores")
  }
  
  z = (x-mean(x)) / sd(x)
  
  z
  
  
  
}
```

```{r, error = TRUE}
z_score(x=3)

z_score(c("my", "name", "is", "jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)
```
